### ISSUE TITLE
Want to integrate lab into webpack flow

### ISSUE THREAD

**Issue by ChenPaulYu** [lo-th/lab#1]
Hello lo-th, 
I am a beginner who is learning how to use ammo.js and three.js now.
I am fascinated by your fantastic work for integrate ammo.js and three.js.
I am thinking about if i can use lab for my development, it will be wonderful.
However, I am using the webpack to bundle my code, do you have any idea about how to take your lab library to webpack flow ?

**Comment by lo-th** [comment]
Yes you can use lab
but i don't give support for webpack
I do not really like this vision of the code... type safety bored me.
